In [16]:
#Simple Python Programming questions - The very first step in any interview 
    #Beginner Level: 
        #80% - Practice your own code 
        #20% - Read others code 
    #Mid Level 
        #50% - Practice your own code 
        #50% - Read others code 
    #Expert Level 
        #30% - Practice your own code 
        #70% - Read others code 

Tackle few simple problems 

    -Break a problem into smaller sub problems 
    -Connecting the dots from sub problems to coding concepts 
    -Code walkthrough and putting it all together 
    -More focus on common errors and mistakes + reading function reference + fixing bugs 

# Problem 1: Add two randomly generate Numpy matrices using loops

In [18]:
#Break into Sub problems
    #1. Generate random matrices 
    #2. Add the matrices 
#Create random matrix A1 of size 5X4
###Google "Numpy create random matrices" and read first few links to get the solution 
###https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/
###https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html

In [30]:
import numpy as np
print('Scalar')
print(np.random.rand())
print()
print('Vector')
print(np.random.rand(3))
print()
print('Matrix')
print(np.random.rand(3,2))

Scalar
0.7522722453453843

Vector
[0.59828879 0.08257196 0.64274439]

Matrix
[[0.10512235 0.42255592]
 [0.34238415 0.57605849]
 [0.71074587 0.07058507]]


In [34]:
#Difference between print(np.random.rand(3,2)) and print(np.random.rand(2,3))

In [56]:
A1 = np.random.rand(5,4)
print(A1.shape()) #Common Error
#We typically call functions and looks like shape is not a function, but why it is saying tuple. We need to understand the same.

TypeError: 'tuple' object is not callable

In [58]:
print(A1.shape) #Attribute and not method

(5, 4)


In [57]:
print(A1.type)

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [48]:
#Explaining the class and objects and attributes - Class came from software engineering 
class Ctof: #Class
    def __init__(self,c):
        self.c = c #Attribute 
    def ctof(self): #Methods
        f = (self.c * 9/5) + 32
        print(f)
c1 = Ctof(10) #c1 is object
c1.ctof()

50.0


In [46]:
#A1 is a variable of numpy.ndarray class

In [47]:
x = 10 
print(type(x))

<class 'int'>


In [55]:
#https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
#Shape is an attribute which return tuple of integers its not a function its just a tuple
#Type attribute is not present 

In [62]:
A2 = np.random.rand(5,4)
print(A2.shape) 

(5, 4)


In [65]:
A1 #Matrices should be of same size then only we can add

array([[0.566609  , 0.09210166, 0.67377608, 0.94733885],
       [0.05538097, 0.05462301, 0.08691125, 0.68666414],
       [0.69514455, 0.84979309, 0.42158615, 0.16751564],
       [0.26149942, 0.00681318, 0.20062527, 0.94079969],
       [0.8689469 , 0.6279964 , 0.07402948, 0.97560874]])

In [64]:
A2

array([[0.27062716, 0.91815619, 0.33402003, 0.11756194],
       [0.06372635, 0.89236568, 0.06375337, 0.32542398],
       [0.28772377, 0.47532044, 0.41147547, 0.09559796],
       [0.90299374, 0.20183697, 0.17102443, 0.13219632],
       [0.38587244, 0.26870613, 0.85447901, 0.11139454]])

In [66]:
print(A1[2,3])

0.16751564184391


In [68]:
print(A1(2,3)) #Common error

TypeError: 'numpy.ndarray' object is not callable

In [71]:
#Bij = A1ij + A2ij
#https://numpy.org/doc/stable/reference/arrays.ndarray.html

In [81]:
B = A1 + A2
print(B)

[[0.83723616 1.01025785 1.00779611 1.06490079]
 [0.11910732 0.94698869 0.15066462 1.01208812]
 [0.98286832 1.32511353 0.83306161 0.2631136 ]
 [1.16449317 0.20865015 0.37164969 1.072996  ]
 [1.25481934 0.89670253 0.92850849 1.08700328]]


In [86]:
#Dynamically changing the matrix size this may lead to some optimization problems 
(r,c) = A1.shape
for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j]
print(B)

[[0.83723616 1.01025785 1.00779611 1.06490079]
 [0.11910732 0.94698869 0.15066462 1.01208812]
 [0.98286832 1.32511353 0.83306161 0.2631136 ]
 [1.16449317 0.20865015 0.37164969 1.072996  ]
 [1.25481934 0.89670253 0.92850849 1.08700328]]


In [88]:
#Optimization: Pre allocated matrix B 
B = np.zeros(5,4) #Common error
#https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

TypeError: Cannot interpret '4' as a data type

In [84]:
#Optimization: Pre allocated matrix B 
B = np.zeros((5,4))

In [85]:
B = np.zeros((5,4))

for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.83723616 1.01025785 1.00779611 1.06490079]
 [0.11910732 0.94698869 0.15066462 1.01208812]
 [0.98286832 1.32511353 0.83306161 0.2631136 ]
 [1.16449317 0.20865015 0.37164969 1.072996  ]
 [1.25481934 0.89670253 0.92850849 1.08700328]]


In [91]:
#Time complexity - O(rXc)
#Space complexity - we created following variables i,j,r,c - O(1) - Space complexity is constant, 
#apart from input and output what variables we used 

In [92]:
#Exercise you participants: B[i,j,k] = A1[i,j,k] + A2[i,j,k]

# Problem 2: Find if a given 2D-point is inside or outside a circle

In [93]:
#Break into Sub problems
    #Represent a circle with x and y coordinate and radius, Cx, Cy and r
    #If the distance between center and point is more than r then it is outside the circle else inside

In [96]:
import sys
print(sys.version)

3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]


In [102]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

(Cx,Cy,r) = [int(x) for x in input('Enter 3 numbers').split()]


Enter 3 numbers0 0 5


In [103]:
Cx

0

In [106]:
# Input Px, Py

(Px, Py) = [int(x) for x in input('Enter 2 numbers').split()]
print(Px, Py);

Enter 2 numbers0 0
0 0


In [107]:
# Check if P lies in C.
d = ( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

0
P in C


In [108]:
#Exercise for participants: If a point present inside or outside the rectangle

# Problem 3: Numpy ndarray manipulation operations

In [125]:
#1. Reshape matrices: Very common errors
A = np.random.rand(5,4)
print('Matrix')
print(A)
#Converting the matrix to vector 
print()
print('Vector')
print(np.reshape(A,20,'C')) #C is row major order , #F - Column major order
#https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
print()
print('2X10 Matrix')
print(np.reshape(A, (2,-1)))
print()
print('2X10 Matrix')
print(np.reshape(A, (2,10)))

Matrix
[[0.92888887 0.94130124 0.44459377 0.2147101 ]
 [0.04477325 0.68516973 0.39432148 0.1088709 ]
 [0.17121965 0.85938037 0.81937368 0.18321255]
 [0.48756457 0.02993338 0.94333098 0.06200544]
 [0.83073519 0.0664809  0.36993257 0.10226748]]

Vector
[0.92888887 0.94130124 0.44459377 0.2147101  0.04477325 0.68516973
 0.39432148 0.1088709  0.17121965 0.85938037 0.81937368 0.18321255
 0.48756457 0.02993338 0.94333098 0.06200544 0.83073519 0.0664809
 0.36993257 0.10226748]

2X10 Matrix
[[0.92888887 0.94130124 0.44459377 0.2147101  0.04477325 0.68516973
  0.39432148 0.1088709  0.17121965 0.85938037]
 [0.81937368 0.18321255 0.48756457 0.02993338 0.94333098 0.06200544
  0.83073519 0.0664809  0.36993257 0.10226748]]

2X10 Matrix
[[0.92888887 0.94130124 0.44459377 0.2147101  0.04477325 0.68516973
  0.39432148 0.1088709  0.17121965 0.85938037]
 [0.81937368 0.18321255 0.48756457 0.02993338 0.94333098 0.06200544
  0.83073519 0.0664809  0.36993257 0.10226748]]


In [126]:
print(np.reshape(A, (4,6)))

ValueError: cannot reshape array of size 20 into shape (4,6)

In [132]:
#Stacking - Horizontal stacking
A = np.random.rand(5,4)
print(A)
print()
B = np.random.rand(5,2)
print(B)

[[0.89577567 0.20289853 0.71214576 0.67539362]
 [0.23555103 0.30327781 0.00737099 0.28477759]
 [0.77759151 0.91454186 0.7997354  0.41157741]
 [0.08220154 0.88945347 0.96845891 0.47757042]
 [0.63685069 0.19997395 0.94272509 0.48385914]]

[[0.22733482 0.72614556]
 [0.43847812 0.46187102]
 [0.82571875 0.1552335 ]
 [0.69425186 0.99541757]
 [0.2424983  0.33034623]]


In [135]:
C = np.hstack(A,B)
print(C)
#https://numpy.org/doc/stable/reference/generated/numpy.hstack.html

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [137]:
C = np.hstack((A,B))
print(C)

[[0.89577567 0.20289853 0.71214576 0.67539362 0.22733482 0.72614556]
 [0.23555103 0.30327781 0.00737099 0.28477759 0.43847812 0.46187102]
 [0.77759151 0.91454186 0.7997354  0.41157741 0.82571875 0.1552335 ]
 [0.08220154 0.88945347 0.96845891 0.47757042 0.69425186 0.99541757]
 [0.63685069 0.19997395 0.94272509 0.48385914 0.2424983  0.33034623]]


In [143]:
#Stacking - Vertical stacking
A = np.random.rand(5,4)
print(A)
print()
B = np.random.rand(2,4)
print(B)
C = print(np.vstack((A,B)))

[[0.21561165 0.63618203 0.32506536 0.45117427]
 [0.60980858 0.40838283 0.09656805 0.19454285]
 [0.98242218 0.44569581 0.82373021 0.75632235]
 [0.88960863 0.9495265  0.09460492 0.83273345]
 [0.10941554 0.8823901  0.00907646 0.52999921]]

[[0.96946346 0.35452831 0.53558101 0.02268937]
 [0.62019522 0.21220152 0.23974054 0.27365779]]
[[0.21561165 0.63618203 0.32506536 0.45117427]
 [0.60980858 0.40838283 0.09656805 0.19454285]
 [0.98242218 0.44569581 0.82373021 0.75632235]
 [0.88960863 0.9495265  0.09460492 0.83273345]
 [0.10941554 0.8823901  0.00907646 0.52999921]
 [0.96946346 0.35452831 0.53558101 0.02268937]
 [0.62019522 0.21220152 0.23974054 0.27365779]]
